create database depositcustomer;
use depositcustomer;

CREATE TABLE CUSTOMERS (
    CNAME VARCHAR(25) PRIMARY KEY,
    CITY VARCHAR(25)
);

CREATE TABLE DEPOSIT (
    LOANNO VARCHAR(10) PRIMARY KEY,
    CNAME VARCHAR(25) REFERENCES CUSTOMERS(CNAME),
    BNAME VARCHAR(25) REFERENCES BRANCH(BNAME),
    AMOUNT INT(10,2)
);

INSERT INTO CUSTOMERS (CNAME, CITY) VALUES
('Anil', 'Calicut'),
('Sunil', 'Kochi'),
('Ravi', 'Calicut'),
('Raj', 'Mumbai'),
('Arun', 'Kochi');

INSERT INTO DEPOSIT (LOANNO, CNAME, BNAME, AMOUNT) VALUES
('L001', 'Anil', 'SBT', 5000),
('L002', 'Sunil', 'SBT', 10000),
('L003', 'Ravi', 'ICICI', 3000),
('L004', 'Raj', 'HDFC', 2000),
('L005', 'Arun', 'SBI', 8000);

SELECT D.CNAME
FROM DEPOSIT D
JOIN CUSTOMERS C ON D.CNAME = C.CNAME
WHERE C.CITY = (SELECT CITY FROM CUSTOMERS WHERE CNAME = 'Anil') 
AND D.AMOUNT > 2000;

SELECT CNAME FROM CUSTOMERS WHERE CITY = 'Calicut';

SELECT DISTINCT C.CITY
FROM CUSTOMERS C
JOIN DEPOSIT D ON C.CNAME = D.CNAME
WHERE D.BNAME = 'SBT' AND C.CITY = 'Calicut';

SELECT D.CNAME
FROM DEPOSIT D
JOIN CUSTOMERS C ON D.CNAME = C.CNAME
WHERE C.CITY = (SELECT CITY FROM CUSTOMERS WHERE CNAME = 'Anil') 
AND D.AMOUNT < 50000;


SELECT SUM(D.AMOUNT)
FROM DEPOSIT D
JOIN CUSTOMERS C ON D.CNAME = C.CNAME
WHERE C.CITY = 'Calicut';


SELECT MAX(D.AMOUNT)
FROM DEPOSIT D
JOIN CUSTOMERS C ON D.CNAME = C.CNAME
WHERE C.CITY = 'Calicut';

SELECT SUM(D.AMOUNT)
FROM DEPOSIT D
JOIN CUSTOMERS C ON D.CNAME = C.CNAME
WHERE C.CITY = (SELECT CITY FROM CUSTOMERS WHERE CNAME = 'Sunil');
