CREATE DATABSE EMPDEPT;

USE EMPDEPT;

CREATE TABLE EMP (
    EMPNO INT PRIMARY KEY,
    ENAME VARCHAR(30),
    JOB VARCHAR(10),
    MGR INT,
    HIREDATE DATE,
    SAL FLOAT,
    COMM FLOAT,
    DEPTNO INT
);

CREATE TABLE DEPT (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(15),
    LOC VARCHAR(15)
);

CREATE TABLE SALGRADE (
    GRADE INT PRIMARY KEY,
    LOSAL INT,
    HSAL INT
);


INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES
(1, 'SMITH', 'CLERK', NULL, '1980-12-01', 800, NULL, 10),
(2, 'ALLEN', 'SALESMAN', 1, '1981-03-01', 1600, 300, 30),
(3, 'WARD', 'SALESMAN', 1, '1981-07-01', 1250, 500, 30),
(4, 'JONES', 'MANAGER', NULL, '1980-06-01', 2975, NULL, 20),
(5, 'MARTIN', 'SALESMAN', 4, '1981-09-01', 1250, 1400, 30);


INSERT INTO DEPT (DEPTNO, DNAME, LOC) VALUES
(10, 'ACCOUNTING', 'NEW YORK'),
(20, 'RESEARCH', 'DALLAS'),
(30, 'SALES', 'CHICAGO'),
(40, 'OPERATIONS', 'BOSTON'),
(50, 'MARKETING', 'LOS ANGELES');


INSERT INTO SALGRADE (GRADE, LOSAL, HSAL) VALUES
(1, 700, 1200),
(2, 1201, 1400),
(3, 1401, 2000),
(4, 2001, 3000),
(5, 3001, 5000);

SELECT * FROM SALGRADE;

SELECT * FROM EMP;

SELECT * FROM EMP
WHERE SAL BETWEEN 1000 AND 2000;

SELECT DNAME, DEPTNO
FROM DEPT
ORDER BY DNAME;

SELECT * FROM EMP
WHERE DEPTNO IN (10, 20);


SELECT ENAME, JOB
FROM EMP
WHERE JOB = 'CLERK' AND DEPTNO = 20;


SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%TH%' OR ENAME LIKE '%LL%';

SELECT ENAME, JOB, SAL
FROM EMP
WHERE MGR IS NOT NULL;

SELECT ENAME, SAL * 12 AS ANNUAL_REMU
FROM EMP;


SELECT ENAME, HIREDATE
FROM EMP
WHERE YEAR(HIREDATE) = 1987;

SELECT ENAME, JOB, SAL * 12 AS ANNUAL_SALARY, COMM
FROM EMP
WHERE JOB = 'SALESMAN' AND SAL > COMM
ORDER BY SAL DESC;

SELECT ENAME, ROUND(SAL * 1.125) AS NEW_SALARY
FROM EMP;


SELECT ENAME AS EMPLOYEE, JOB
FROM EMP;

ALTER TABLE EMP ADD COLUMN SEX CHAR(1);


SELECT ENAME, JOB
FROM EMP
WHERE DEPTNO = 30 AND JOB = 'SALESMAN' AND SEX != 'M';

SELECT ENAME, JOB
FROM EMP
WHERE DEPTNO = 30 AND JOB = 'SALESMAN';






